### ISSUE TITLE
Return instead of Print!  #1

### ISSUE THREAD

**Issue by kaushiksk** [kaushiksk/pymdb#1]
The _director(), actor(), awards()_ helper functions currently just print strings.
It would be better if they'd return these strings to the caller so that they can be used further or stored in variables.

**Comment by vharsh** [comment]
On it.

**Comment by vharsh** [comment]
I found a bug. I executed.

```
>>> import pymdb
>>> ids = pymdb.top250_id()
>>> for id in ids:
...     m = pymdb.MovieId(id)
...     m.getposter()
... 
```

and got

```
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "pymdb.py", line 113, in getposter
    outfile = open('%s.jpg'%self.stuff.find('movie').get("title").translate(None, string.punctuation), 'wb')
TypeError: translate() takes exactly one argument (2 given)
```

Should I fix this one in the same branch?
